# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      # Format Python files
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # Clean up trailing whitespace
      - id: trailing-whitespace

      # Ensure files have a proper EOL
      - id: end-of-file-fixer

      # All non-bat files should end with LF
      - id: mixed-line-ending
        name: Ensure LF endings on most files
        args: ['--fix=lf']
        exclude: \.bat$

      # Bat files should be CRLF ending
      - id: mixed-line-ending
        name: Ensure CFLF endings on Windows files
        args: ['--fix=crlf']
        files: \.bat$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      # Do a security scan with Bandit
      - id: bandit
        args: ['--ini', '.bandit', '-r']
        exclude: |
          (?x)^(
            .*/tests/.*
          )$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      # Run prettier to format non-Python files
      - id: prettier
        additional_dependencies:
          - prettier@2.6.2
          - prettier-plugin-svelte@2.7.0
        exclude: |
          (?x)^(
            .*/pnpm-lock.yaml$
          )$
