name: Build and deploy

on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Build frontend
        run: |
          pnpm run build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "<noreply@github.com>"
