name: Build and deploy

on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: poetry install

      - name: Build frontend
        run: |
          cd vocabulary-trainer
          cd frontend
          pnpm run build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "<noreply@github.com>"
